#include <stdio.h>

void concatenate (char s1[], char s2[], char s[])
{
    int i = 0, j = 0;
    while (s1 [i] != '\0')
    {
        s [i] = s1 [i];
        i++;
    }
    while (s2 [j] != '\0')
    {
        s [i] = s2 [j];
        i++;
        j++;
    }
    s [i] = '\0';
}

int main()
{
    char s1[50], s2[50];
    printf ("Enter the string 1: ");
    scanf ("%50[^\n]", s1);
    getchar();                          //To absorb the '\n' generated by the previous scanf(). Otherwise the next scanf() will take that '\n' as input and terminate the reading.
    printf ("Enter the string 2: ");
    scanf ("%50[^\n]", s2);
    
    int c1 = 0, c2 = 0;
    while (s1 [++c1] != '\0');
    while (s2 [++c2] != '\0');
    char s [c1 + c2 + 1];
    concatenate (s1, s2, s);
    printf ("The original strings are:\n%s\n%s\n", s1, s2);
    printf ("The concatenated string is: %s\n", s);
    return 0;
}
